### PR TITLE
fix(svg): stroke-width was missing in the svg data

### PR DESCRIPTION
**Pull request by Kerumen**
Hello,

Nice project!
I noticed while using it that the stroke-width was missing in the v2. I just copied it from the v1 to the v2. :)

Cheers

### CODE REVIEW

**Comment by enjikaka** [comment]
Hi!

I do not think it's needed though. I'll investigate. Thanks!

**Comment by Kerumen** [comment]
The width parameter was not working for me without this.

**Comment by enjikaka** [comment]
Okay. I'll look into it b4 eventually merging! :) Will probably do it next weekend!

**Comment by Kerumen** [comment]
Okey! I checked all the differences between v1 and v2 and I don't understand how the width parameter can work (in the v2) without this fix but maybe I am wrong.

**Comment by Kerumen** [comment]
Any updates about this?

**Comment by enjikaka** [comment]
I tried messing with the width and gap about a week ago. Seemed to work fine.
I haven't had time to look at it any further yet. I'll get back to you when I have. :)

**Comment by Kerumen** [comment]
Even on the v2 ?

**Comment by Kerumen** [comment]
ALLO ALLO ALLO

**Pull request merged**
